version: '3.9'

services:
  redis:
    image: redis:8.0-alpine  # 2026 年开源稳定版
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: >
      redis-server
      --requirepass 11111111
      --save 60 1
      --loglevel warning
      --maxmemory 2gb
      --maxmemory-policy allkeys-lru  # 自动移除冷键
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "11111111", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    ports:
      - "8001:8001"
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - app-network

  postgres:
    image: postgres:18-alpine  # 支持增量物化视图
    container_name: postgres
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-pg.sql:/docker-entrypoint-initdb.d/init.sql  # 可选初始脚本
    command: >
      postgres
      -c wal_level=logical
      -c max_replication_slots=10
      -c max_wal_senders=10
      -c max_logical_replication_workers=10
      -c listen_addresses='*'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d testdb"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  debezium:
    image: debezium/server:3.4  # 2026 年最新稳定版
    container_name: debezium
    ports:
      - "8080:8080"
    volumes:
      - ./debezium-conf/application.properties:/debezium/conf/application.properties
      - debezium-data:/debezium/data
    environment:
      - ENABLE_DEBEZIUM_SCRIPTING=true
      - JAVA_OPTS=-Xmx1g -Xms512m
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - app-network

volumes:
  redis-data:
  postgres-data:
  debezium-data:

networks:
  app-network:
    driver: bridge
